language: minimal
stages:
  - test
  - name: 'deploy pages'
    if: branch = master
  - name: 'deploy release'
    if: tag IS present
script:
  - make test
before_deploy:
  - mkdir -p public
  - touch public/index.html
  - echo 'hello from template' > public/index.html
jobs:
  include:
    - stage: 'deploy pages'
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
        committer_from_gh: true
        local_dir: public
        on:
          branch: master
    - stage: 'deploy release'
      before_deploy:
        - if [[ $(git tag -l '*' | wc -l) == "1" ]]; then
            export BODY="See [changelog](https://github.com/deild/travisci/commits/$TRAVIS_TAG)";
          else
            export BODY="See [changelog](https://github.com/deild/travisci/compare/$(git tag -l '*' | tail -n2 | head -n1)...$TRAVIS_TAG)";
          fi
        - tar -czf www.tar.xz public/index.html
        - sha256sum www.tar.xz > www.tar.xz.sha256
      deploy:
        provider: releases
        overwrite: true
        api_key: $GITHUB_TOKEN
        file_glob: true
        file:
          - "*.tar.xz"
          - "*.sha256"
        skip_cleanup: true
        body: $BODY
        on:
          repo: deild/travisci
          tags: true
