language: minimal

git:
  quiet: true

install: skip

script:
  - make build
  - mkdir -p public
  - touch public/index.html
  - echo 'hello from template' > public/index.html

before_deploy:
  - npm install -g auto-changelog
  - auto-changelog

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    name: $GITHUB_USERNAME
    email: $GITHUB_EMAIL
    local_dir: public
    on:
      branch: master
  - provider: releases
    api_key: $GITHUB_TOKEN
    file:
      - "public/*"
      - "CHANGELOG.md"
    skip_cleanup: true
    on:
      tags: true